export const MOCK_QUIZZES = {
  'practice-1': {
    quizId: 'practice-1',
    title: 'JavaScript Fundamentals',
    description: 'Test your knowledge of JavaScript basics including variables, types, and functions.',
    timerMode: 'NONE',
    questions: [
      {
        id: 'p1',
        content: 'Which keyword is used to declare a constant in JavaScript?',
        type: 'SINGLE_CHOICE',
        difficulty: 'EASY',
        score: 10,
        explanation: 'The "const" keyword was introduced in ES6 to declare variables whose values cannot be reassigned after initialization.',
        answers: [
          { id: 'p1a', content: 'var', isCorrect: false },
          { id: 'p1b', content: 'let', isCorrect: false },
          { id: 'p1c', content: 'const', isCorrect: true },
          { id: 'p1d', content: 'define', isCorrect: false },
        ],
      },
      {
        id: 'p2',
        content: 'Which of the following are JavaScript primitive types? (Select all)',
        type: 'MULTIPLE_CHOICE',
        difficulty: 'EASY',
        score: 15,
        explanation: 'JavaScript has 7 primitive types: string, number, bigint, boolean, undefined, symbol, and null.',
        answers: [
          { id: 'p2a', content: 'String', isCorrect: true },
          { id: 'p2b', content: 'Boolean', isCorrect: true },
          { id: 'p2c', content: 'Float', isCorrect: false },
          { id: 'p2d', content: 'Undefined', isCorrect: true },
        ],
      },
      {
        id: 'p3',
        content: 'What does the "===" operator check in JavaScript?',
        type: 'SINGLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 10,
        explanation: 'The strict equality operator (===) checks both value AND type, unlike == which performs type coercion.',
        answers: [
          { id: 'p3a', content: 'Only value equality', isCorrect: false },
          { id: 'p3b', content: 'Value and type equality', isCorrect: true },
          { id: 'p3c', content: 'Only type equality', isCorrect: false },
          { id: 'p3d', content: 'Reference equality only', isCorrect: false },
        ],
      },
      {
        id: 'p4',
        content: 'What is a closure in JavaScript?',
        type: 'SINGLE_CHOICE',
        difficulty: 'HARD',
        score: 20,
        explanation: 'A closure is a function that retains access to its outer (enclosing) function\'s variables even after the outer function has returned.',
        answers: [
          { id: 'p4a', content: 'A way to close browser windows', isCorrect: false },
          { id: 'p4b', content: 'A function that accesses variables from its outer scope', isCorrect: true },
          { id: 'p4c', content: 'A method to end loops', isCorrect: false },
          { id: 'p4d', content: 'A type of error handling', isCorrect: false },
        ],
      },
      {
        id: 'p5',
        content: 'Which of the following are JavaScript array methods? (Select all)',
        type: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 15,
        explanation: 'map(), filter(), and reduce() are built-in array methods. "transform" is not a standard array method.',
        answers: [
          { id: 'p5a', content: 'map()', isCorrect: true },
          { id: 'p5b', content: 'filter()', isCorrect: true },
          { id: 'p5c', content: 'reduce()', isCorrect: true },
          { id: 'p5d', content: 'transform()', isCorrect: false },
        ],
      },
    ],
  },

  'exam-total-1': {
    quizId: 'exam-total-1',
    title: 'React Essentials',
    description: 'Comprehensive exam covering React core concepts, hooks, and state management.',
    timerMode: 'TOTAL',
    totalTime: 1200,
    questions: [
      {
        id: 'e1',
        content: 'What is JSX in React?',
        type: 'SINGLE_CHOICE',
        difficulty: 'EASY',
        score: 10,
        explanation: 'JSX is a syntax extension for JavaScript that allows writing HTML-like code in JavaScript files.',
        answers: [
          { id: 'e1a', content: 'A CSS preprocessor', isCorrect: false },
          { id: 'e1b', content: 'A JavaScript syntax extension for UI', isCorrect: true },
          { id: 'e1c', content: 'A database query language', isCorrect: false },
          { id: 'e1d', content: 'A testing framework', isCorrect: false },
        ],
      },
      {
        id: 'e2',
        content: 'Which of the following are built-in React hooks? (Select all)',
        type: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 15,
        explanation: 'useState, useEffect, and useMemo are all built-in React hooks. useStore is not a built-in hook.',
        answers: [
          { id: 'e2a', content: 'useState', isCorrect: true },
          { id: 'e2b', content: 'useEffect', isCorrect: true },
          { id: 'e2c', content: 'useMemo', isCorrect: true },
          { id: 'e2d', content: 'useStore', isCorrect: false },
        ],
      },
      {
        id: 'e3',
        content: 'What is the primary purpose of useEffect?',
        type: 'SINGLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 10,
        explanation: 'useEffect is used to handle side effects like API calls, subscriptions, and DOM manipulation.',
        answers: [
          { id: 'e3a', content: 'Managing component state', isCorrect: false },
          { id: 'e3b', content: 'Handling side effects', isCorrect: true },
          { id: 'e3c', content: 'Styling components', isCorrect: false },
          { id: 'e3d', content: 'Routing between pages', isCorrect: false },
        ],
      },
      {
        id: 'e4',
        content: 'What is the Virtual DOM?',
        type: 'SINGLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 10,
        explanation: 'The Virtual DOM is a lightweight JavaScript representation of the real DOM that React uses to optimize re-renders.',
        answers: [
          { id: 'e4a', content: 'A browser API', isCorrect: false },
          { id: 'e4b', content: 'A lightweight copy of the real DOM', isCorrect: true },
          { id: 'e4c', content: 'A CSS rendering engine', isCorrect: false },
          { id: 'e4d', content: 'A database system', isCorrect: false },
        ],
      },
      {
        id: 'e5',
        content: 'Which are valid React state management solutions? (Select all)',
        type: 'MULTIPLE_CHOICE',
        difficulty: 'HARD',
        score: 20,
        explanation: 'Redux, Context API, and Zustand are all valid state management solutions in React.',
        answers: [
          { id: 'e5a', content: 'Redux', isCorrect: true },
          { id: 'e5b', content: 'Context API', isCorrect: true },
          { id: 'e5c', content: 'Zustand', isCorrect: true },
          { id: 'e5d', content: 'jQuery State', isCorrect: false },
        ],
      },
    ],
  },

  'exam-per-1': {
    quizId: 'exam-per-1',
    title: 'CSS Mastery',
    description: 'Timed exam with per-question time limits covering advanced CSS concepts.',
    timerMode: 'PER_QUESTION',
    questions: [
      {
        id: 'c1',
        content: 'What is the correct order of the CSS box model from outside to inside?',
        type: 'SINGLE_CHOICE',
        difficulty: 'EASY',
        score: 10,
        timeLimit: 60,
        explanation: 'The CSS box model layers from outside to inside: margin → border → padding → content.',
        answers: [
          { id: 'c1a', content: 'padding, margin, border, content', isCorrect: false },
          { id: 'c1b', content: 'margin, border, padding, content', isCorrect: true },
          { id: 'c1c', content: 'content, padding, border, margin', isCorrect: false },
          { id: 'c1d', content: 'border, margin, padding, content', isCorrect: false },
        ],
      },
      {
        id: 'c2',
        content: 'What does "display: flex" do?',
        type: 'SINGLE_CHOICE',
        difficulty: 'EASY',
        score: 10,
        timeLimit: 45,
        explanation: 'display: flex creates a flex container, enabling flexible layout of its direct children.',
        answers: [
          { id: 'c2a', content: 'Creates a grid layout', isCorrect: false },
          { id: 'c2b', content: 'Creates a flex container', isCorrect: true },
          { id: 'c2c', content: 'Hides the element', isCorrect: false },
          { id: 'c2d', content: 'Makes element inline', isCorrect: false },
        ],
      },
      {
        id: 'c3',
        content: 'Which are valid CSS position values? (Select all)',
        type: 'MULTIPLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 15,
        timeLimit: 60,
        explanation: 'relative, absolute, fixed, sticky, and static are valid CSS position values.',
        answers: [
          { id: 'c3a', content: 'relative', isCorrect: true },
          { id: 'c3b', content: 'absolute', isCorrect: true },
          { id: 'c3c', content: 'fixed', isCorrect: true },
          { id: 'c3d', content: 'floating', isCorrect: false },
        ],
      },
      {
        id: 'c4',
        content: 'The z-index property only works on which type of elements?',
        type: 'SINGLE_CHOICE',
        difficulty: 'MEDIUM',
        score: 10,
        timeLimit: 30,
        explanation: 'z-index only works on positioned elements (position: relative, absolute, fixed, or sticky).',
        answers: [
          { id: 'c4a', content: 'All elements', isCorrect: false },
          { id: 'c4b', content: 'Block elements only', isCorrect: false },
          { id: 'c4c', content: 'Positioned elements', isCorrect: true },
          { id: 'c4d', content: 'Inline elements only', isCorrect: false },
        ],
      },
      {
        id: 'c5',
        content: 'What is the correct CSS specificity order (highest to lowest)?',
        type: 'SINGLE_CHOICE',
        difficulty: 'HARD',
        score: 20,
        timeLimit: 45,
        explanation: 'CSS specificity from highest to lowest: inline styles > ID selectors > class selectors > element selectors.',
        answers: [
          { id: 'c5a', content: 'class > ID > inline > element', isCorrect: false },
          { id: 'c5b', content: 'inline > ID > class > element', isCorrect: true },
          { id: 'c5c', content: 'ID > inline > element > class', isCorrect: false },
          { id: 'c5d', content: 'element > class > ID > inline', isCorrect: false },
        ],
      },
    ],
  },
};

export const getQuizById = (quizId) => MOCK_QUIZZES[quizId] || null;
