import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..');
const OUTPUT_FILE = path.join(REPO_ROOT, 'public', 'sitemap.xml');

const SITE_URL = (process.env.SITE_URL ?? 'https://quizmateai.io.vn').replace(/\/$/, '');
const POLICIES_API_URL =
  process.env.POLICIES_API_URL ?? 'https://api.quizmateai.io.vn/api/policies/public';

const LANGUAGES = ['vi', 'en', 'ja'];
const DEFAULT_LANGUAGE = 'vi';

const STATIC_ROUTES = [
  { path: '/', changefreq: 'weekly', priority: '1.0' },
  { path: '/policies', changefreq: 'monthly', priority: '0.7' },
];

function buildLanguageUrl(pathname, language) {
  const url = new URL(pathname, `${SITE_URL}/`);
  if (language !== DEFAULT_LANGUAGE) {
    url.searchParams.set('lang', language);
  }
  return url.toString();
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function renderHreflangBlock(pathname, indent) {
  const pad = ' '.repeat(indent);
  const links = LANGUAGES.map((lang) => {
    const href = escapeXml(buildLanguageUrl(pathname, lang));
    return `${pad}<xhtml:link rel="alternate" hreflang="${lang}" href="${href}" />`;
  });
  const xDefault = escapeXml(buildLanguageUrl(pathname, DEFAULT_LANGUAGE));
  links.push(`${pad}<xhtml:link rel="alternate" hreflang="x-default" href="${xDefault}" />`);
  return links.join('\n');
}

function renderRouteEntries(pathname, changefreq, priority) {
  return LANGUAGES.map((lang) => {
    const loc = escapeXml(buildLanguageUrl(pathname, lang));
    return [
      '  <url>',
      `    <loc>${loc}</loc>`,
      renderHreflangBlock(pathname, 4),
      `    <changefreq>${changefreq}</changefreq>`,
      `    <priority>${priority}</priority>`,
      '  </url>',
    ].join('\n');
  }).join('\n\n');
}

async function fetchPublicPolicies() {
  try {
    const response = await fetch(POLICIES_API_URL, {
      headers: { Accept: 'application/json' },
    });
    if (!response.ok) {
      console.warn(
        `[sitemap] BE policies endpoint returned ${response.status} — skipping policy entries.`,
      );
      return [];
    }
    const payload = await response.json();
    const list = Array.isArray(payload) ? payload : payload?.data ?? [];
    return list
      .map((policy) => policy?.slug)
      .filter((slug) => typeof slug === 'string' && slug.length > 0);
  } catch (error) {
    console.warn('[sitemap] Failed to fetch policies — skipping policy entries.', error.message);
    return [];
  }
}

async function main() {
  const policySlugs = await fetchPublicPolicies();
  console.log(`[sitemap] Fetched ${policySlugs.length} published policy slugs.`);

  const staticEntries = STATIC_ROUTES.map((route) =>
    renderRouteEntries(route.path, route.changefreq, route.priority),
  );
  const policyEntries = policySlugs.map((slug) =>
    renderRouteEntries(`/policies/${encodeURIComponent(slug)}`, 'monthly', '0.6'),
  );

  const body = [...staticEntries, ...policyEntries].join('\n\n');

  const output = `<?xml version="1.0" encoding="UTF-8"?>
<!--
  Quizmate AI sitemap — generated by scripts/generate-sitemap.mjs.
  Do not edit by hand; run \`npm run sitemap\` to regenerate.
  Last generated: ${new Date().toISOString()}
-->
<urlset
  xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml">

${body}

</urlset>
`;

  await fs.writeFile(OUTPUT_FILE, output, 'utf8');
  console.log(`[sitemap] Wrote ${OUTPUT_FILE}`);
}

main().catch((error) => {
  console.error('[sitemap] Fatal error:', error);
  process.exit(1);
});
